# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 성공
GET http://localhost:8030/admin/menu
Content-Type: application/json
Authorization: Waiter eyJhbGciOiJIUzUxMiJ9.eyJleHAiOjE1MzU2NzQ4ODYsImlkIjoxLCJ1c2VybmFtZSI6Iu2Zjeq4uOuPmSJ9.g8P9-wgtlc5YV_4mNC--An9R6EdnEeM3bjwskceFj00bCfHBVGGNtbZGXW5VPxmeKiOobiMbYv6NVK4cDGDQGA

###

